// A small, dependency-free walker that turns a game's JSON Schema (the "round" $def,
// specifically) into a list of field descriptors the renderer can turn into inputs, and
// back into a plain object for Ajv to validate. No third-party schema-form library —
// the schemas here are overwhelmingly flat string/enum/const/integer/array<string> fields
// (confirmed against all 28 vendored schemas), with a handful of games needing one
// recursive case: an array of nested objects (inline `type: "object"` or `$ref`).

export type JsonSchemaNode = {
  type?: string | string[];
  enum?: string[];
  const?: string;
  minLength?: number;
  minimum?: number;
  minItems?: number;
  maxItems?: number;
  uniqueItems?: boolean;
  items?: JsonSchemaNode;
  properties?: Record<string, JsonSchemaNode>;
  required?: string[];
  additionalProperties?: boolean;
  $ref?: string;
  [key: string]: unknown;
};

export type JsonSchemaDocument = {
  $defs?: Record<string, JsonSchemaNode>;
  [key: string]: unknown;
};

// Field names that read as long-form prose in every schema inspected — these get a
// multi-line textarea instead of a single-line input. The schemas themselves carry no
// multiline/format hint, so this is a small, explicit heuristic list rather than a guess
// baked into the walker's core logic.
const LONG_TEXT_FIELD_NAMES = new Set([
  "teachingNote",
  "verseText",
  "placeholderText",
  "explanation",
  "context",
  "contextClue",
  "verseStart",
  "prompt",
  "fulfillmentText",
  "fulfillmentSummary",
  "fulfillmentTextShort",
  "prophecySummary",
  "prophecyTextShort",
  "excerpt",
  "quote",
  "verseTextShort"
]);

export type FieldKind =
  | "const"
  | "enum"
  | "text"
  | "textarea"
  | "integer"
  | "string-list"
  | "object-list"
  | "nullable-text";

export interface FieldDescriptor {
  name: string;
  kind: FieldKind;
  required: boolean;
  enumValues?: string[];
  constValue?: string;
  minItems?: number;
  maxItems?: number;
  uniqueItems?: boolean;
  // Only for kind === "object-list": the resolved field descriptors for one item's shape.
  itemFields?: FieldDescriptor[];
}

function resolveRef(schemaDocument: JsonSchemaDocument, node: JsonSchemaNode): JsonSchemaNode {
  if (!node.$ref) {
    return node;
  }

  const match = node.$ref.match(/^#\/\$defs\/(.+)$/);
  if (!match) {
    throw new Error(`Unsupported $ref: ${node.$ref}`);
  }

  const resolved = schemaDocument.$defs?.[match[1]];
  if (!resolved) {
    throw new Error(`Could not resolve $ref "${node.$ref}" — no matching $defs entry.`);
  }

  return resolved;
}

function isNullableString(node: JsonSchemaNode): boolean {
  return Array.isArray(node.type) && node.type.includes("string") && node.type.includes("null");
}

function describeField(schemaDocument: JsonSchemaDocument, name: string, node: JsonSchemaNode, requiredFields: Set<string>): FieldDescriptor {
  const required = requiredFields.has(name);

  if (typeof node.const === "string") {
    return { name, kind: "const", required, constValue: node.const };
  }

  if (Array.isArray(node.enum)) {
    return { name, kind: "enum", required, enumValues: node.enum };
  }

  if (isNullableString(node)) {
    return { name, kind: "nullable-text", required };
  }

  if (node.type === "integer" || node.type === "number") {
    return { name, kind: "integer", required };
  }

  if (node.type === "array") {
    const itemNode = node.items ? resolveRef(schemaDocument, node.items) : undefined;

    if (itemNode && itemNode.type === "object" && itemNode.properties) {
      return {
        name,
        kind: "object-list",
        required,
        minItems: node.minItems,
        maxItems: node.maxItems,
        itemFields: describeObjectFields(schemaDocument, itemNode)
      };
    }

    return {
      name,
      kind: "string-list",
      required,
      minItems: node.minItems,
      maxItems: node.maxItems,
      uniqueItems: node.uniqueItems
    };
  }

  if (LONG_TEXT_FIELD_NAMES.has(name)) {
    return { name, kind: "textarea", required };
  }

  return { name, kind: "text", required };
}

// Shared by both the top-level round shape and any nested object-list item shape (e.g. a
// "group" inside bible-connections' "groups") — "id" is generated by the admin console at
// every nesting level, never hand-entered, so it's filtered out here once for both callers.
function describeObjectFields(schemaDocument: JsonSchemaDocument, objectNode: JsonSchemaNode): FieldDescriptor[] {
  if (!objectNode.properties) {
    throw new Error("Schema object node has no properties to describe.");
  }

  const requiredFields = new Set(objectNode.required ?? []);
  return Object.entries(objectNode.properties)
    .filter(([fieldName]) => fieldName !== "id")
    .map(([fieldName, fieldNode]) => describeField(schemaDocument, fieldName, resolveRef(schemaDocument, fieldNode), requiredFields));
}

/**
 * Given a full pack schema document, resolve and describe the "round" $def's fields —
 * the shape a single round of content takes for this game.
 */
export function describeRoundFields(schemaDocument: JsonSchemaDocument): FieldDescriptor[] {
  const roundSchema = schemaDocument.$defs?.round;
  if (!roundSchema || !roundSchema.properties) {
    throw new Error("Schema has no $defs.round.properties — cannot describe round fields.");
  }

  return describeObjectFields(schemaDocument, roundSchema);
}

/** Default/empty value for a freshly-added field, keyed by FieldKind. */
export function emptyValueForField(field: FieldDescriptor): unknown {
  switch (field.kind) {
    case "const":
      return field.constValue;
    case "enum":
      return field.enumValues?.[0] ?? "";
    case "integer":
      return 0;
    case "string-list":
      return [];
    case "object-list":
      return [];
    case "nullable-text":
      return null;
    case "textarea":
    case "text":
    default:
      return "";
  }
}

export function emptyRoundValues(fields: FieldDescriptor[]): Record<string, unknown> {
  const values: Record<string, unknown> = {};
  for (const field of fields) {
    values[field.name] = emptyValueForField(field);
  }
  return values;
}
