import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { describeRoundFields, emptyRoundValues, type JsonSchemaDocument } from "../src/lib/formRenderer";

function loadSchema(fileName: string): JsonSchemaDocument {
  const raw = readFileSync(path.resolve(__dirname, "../src/data/schemas", fileName), "utf8");
  return JSON.parse(raw) as JsonSchemaDocument;
}

describe("formRenderer.describeRoundFields", () => {
  it("describes a flat schema (complete-the-verse) as scalar fields", () => {
    const schema = loadSchema("complete-the-verse.schema.json");
    const fields = describeRoundFields(schema);
    const byName = Object.fromEntries(fields.map((field) => [field.name, field]));

    expect(byName.title.kind).toBe("text");
    expect(byName.book.kind).toBe("enum");
    expect(byName.book.enumValues).toEqual(["Psalms", "Proverbs"]);
    expect(byName.choices.kind).toBe("string-list");
    expect(byName.choices.minItems).toBe(4);
    expect(byName.choices.maxItems).toBe(4);
    expect(byName.difficulty.kind).toBe("enum");
    expect(byName.teachingNote.kind).toBe("textarea");
    // "id" is generated by the admin console, not part of the hand-entered field list
    expect(byName.id).toBeUndefined();
  });

  it("describes an array-of-object field via inline object schema (fulfillment-finder)", () => {
    const schema = loadSchema("fulfillment-finder.schema.json");
    const fields = describeRoundFields(schema);
    const choices = fields.find((field) => field.name === "choices");

    expect(choices?.kind).toBe("object-list");
    expect(choices?.minItems).toBe(4);
    expect(choices?.maxItems).toBe(4);
    const itemFieldNames = choices?.itemFields?.map((field) => field.name);
    expect(itemFieldNames).toEqual(["reference", "summary"]);
    expect(choices?.itemFields?.every((field) => field.kind === "text")).toBe(true);
  });

  it("describes an array-of-object field via $ref (bible-connections)", () => {
    const schema = loadSchema("bible-connections.schema.json");
    const fields = describeRoundFields(schema);
    const groups = fields.find((field) => field.name === "groups");

    expect(groups?.kind).toBe("object-list");
    expect(groups?.minItems).toBe(4);
    expect(groups?.maxItems).toBe(4);
    const itemFieldNames = groups?.itemFields?.map((field) => field.name);
    expect(itemFieldNames).toEqual(["category", "items"]);
    const itemsField = groups?.itemFields?.find((field) => field.name === "items");
    expect(itemsField?.kind).toBe("string-list");
    expect(itemsField?.uniqueItems).toBe(true);
  });

  it("describes a const field and a nullable string field (scripture-puzzles)", () => {
    const schema = loadSchema("scripture-puzzles.schema.json");
    const fields = describeRoundFields(schema);
    const byName = Object.fromEntries(fields.map((field) => [field.name, field]));

    expect(byName.contentMode.kind).toBe("enum");
    expect(byName.contentMode.enumValues).toEqual(["placeholder", "public-domain-text", "licensed-text"]);
    expect(byName.placeholderText.kind).toBe("nullable-text");
    expect(byName.verseText.kind).toBe("nullable-text");
    expect(byName.sourceTranslation.kind).toBe("enum");
  });

  it("marks required fields correctly", () => {
    const schema = loadSchema("complete-the-verse.schema.json");
    const fields = describeRoundFields(schema);
    const byName = Object.fromEntries(fields.map((field) => [field.name, field]));

    expect(byName.title.required).toBe(true);
    expect(byName.teachingNote.required).toBe(true);
  });

  it("produces sensible empty defaults for every field kind", () => {
    const schema = loadSchema("bible-connections.schema.json");
    const fields = describeRoundFields(schema);
    const values = emptyRoundValues(fields);

    expect(values.title).toBe("");
    expect(values.groups).toEqual([]);
    expect(values.difficulty).toBe("easy");
  });
});
